CREATE TABLE trade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    trade_type VARCHAR(255),
    trade_date DATE,
    amount DOUBLE,
    currency VARCHAR(255),
    counterparty VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE crypto_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    symbol VARCHAR(255),
    market_cap DECIMAL(20, 2),
    listing_date DATE,
    PRIMARY KEY (id)
);
