package com.data.service.core.mapper;

import com.data.service.core.model.Account;
import com.data.service.core.model.AccountEntity;

/**
 * Base Mapper generated by Gradle.
 * Do not modify this file. Override methods in AccountMapper instead.
 */
public abstract class AccountMapperBase implements EntityMapper<Account, AccountEntity> {

    public Account toModel(AccountEntity entity) {
        if (entity == null) {
            return null;
        }
        Account model = new Account();

        model.setId(entity.getId());

        model.setAccountName(entity.getAccountName());

        model.setBalance(entity.getBalance());

        return model;
    }

    public AccountEntity toEntity(Account model) {
        if (model == null) {
            return null;
        }
        AccountEntity entity = new AccountEntity();

        entity.setId(model.getId());

        entity.setAccountName(model.getAccountName());

        entity.setBalance(model.getBalance());

        return entity;
    }

}
