package com.data.service.core.mapper;

import com.data.service.core.model.CryptoAsset;
import com.data.service.core.model.CryptoAssetEntity;

/**
 * Base Mapper generated by Gradle.
 * Do not modify this file. Override methods in CryptoAssetMapper instead.
 */
public abstract class CryptoAssetMapperBase implements EntityMapper<CryptoAsset, CryptoAssetEntity> {

    public CryptoAsset toModel(CryptoAssetEntity entity) {
        if (entity == null) {
            return null;
        }
        CryptoAsset model = new CryptoAsset();

        model.setId(entity.getId());

        model.setSymbol(entity.getSymbol());

        model.setMarketCap(entity.getMarketCap());

        model.setListingDate(entity.getListingDate());

        return model;
    }

    public CryptoAssetEntity toEntity(CryptoAsset model) {
        if (model == null) {
            return null;
        }
        CryptoAssetEntity entity = new CryptoAssetEntity();

        entity.setId(model.getId());

        entity.setSymbol(model.getSymbol());

        entity.setMarketCap(model.getMarketCap());

        entity.setListingDate(model.getListingDate());

        return entity;
    }

}
