package com.data.service.core.mapper;

import com.data.service.core.model.Trade;
import com.data.service.core.model.TradeEntity;

/**
 * Base Mapper generated by Gradle.
 * Do not modify this file. Override methods in TradeMapper instead.
 */
public abstract class TradeMapperBase implements EntityMapper<Trade, TradeEntity> {

    public Trade toModel(TradeEntity entity) {
        if (entity == null) {
            return null;
        }
        Trade model = new Trade();

        model.setId(entity.getId());

        model.setTradeType(entity.getTradeType());

        model.setTradeDate(entity.getTradeDate());

        model.setAmount(entity.getAmount());

        model.setCurrency(entity.getCurrency());

        model.setCounterparty(entity.getCounterparty());

        return model;
    }

    public TradeEntity toEntity(Trade model) {
        if (model == null) {
            return null;
        }
        TradeEntity entity = new TradeEntity();

        entity.setId(model.getId());

        entity.setTradeType(model.getTradeType());

        entity.setTradeDate(model.getTradeDate());

        entity.setAmount(model.getAmount());

        entity.setCurrency(model.getCurrency());

        entity.setCounterparty(model.getCounterparty());

        return entity;
    }

}
